# Используем официальный образ Go как базовый
FROM golang:1.22 as builder

# Устанавливаем рабочую директорию в контейнере
WORKDIR /app

# Копируем файлы модулей Go
COPY go.mod go.sum ./

# Скачиваем зависимости
RUN go mod download

# Копируем исходный код
COPY . .

# Собираем бинарный файл
RUN CGO_ENABLED=0 go build -o /bin/myapp

# Используем базовый образ для финального этапа
FROM alpine:latest
WORKDIR /root/

# Копируем бинарник из билдера
COPY --from=builder /bin/myapp .

# Открываем порт, который слушает ваше приложение
EXPOSE 8080

# Запускаем приложение
CMD ["./myapp"]